#Requires -Version 5.1
<#
.SYNOPSIS
    LineOps KDS — Windows Installer

.DESCRIPTION
    Installs the LineOps KDS on a Windows machine using Docker Desktop.
    Run from the root of the repo in an elevated PowerShell session:

        .\install.ps1

    Or with a custom port:

        .\install.ps1 -Port 8080

.PARAMETER Port
    HTTP port to expose on the host (default: 80)

.PARAMETER InstallDir
    Where to copy the KDS files (default: current directory)

.PARAMETER SkipBuild
    Skip rebuilding Docker images (use cached images)
#>
param(
    [int]    $Port       = 80,
    [string] $InstallDir = $PSScriptRoot,
    [switch] $SkipBuild
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

# ── Colours ────────────────────────────────────────────────────────────────────
function Info  ($m) { Write-Host "  -> $m" -ForegroundColor Cyan }
function Ok    ($m) { Write-Host "  OK $m" -ForegroundColor Green }
function Warn  ($m) { Write-Host "  !! $m" -ForegroundColor Yellow }
function Die   ($m) { Write-Host "  ERR $m" -ForegroundColor Red; exit 1 }
function Sec   ($m) { Write-Host ""; Write-Host "-- $m" -ForegroundColor White; Write-Host "" }

# ── Banner ─────────────────────────────────────────────────────────────────────
Write-Host ""
Write-Host "  LineOps KDS -- Windows Installer" -ForegroundColor White
Write-Host "  Powered by Docker Desktop" -ForegroundColor DarkGray
Write-Host ""

# ── Check: Docker ──────────────────────────────────────────────────────────────
Sec "Checking prerequisites"

if (-not (Get-Command docker -ErrorAction SilentlyContinue)) {
    Die @"
Docker Desktop is not installed.
Download it from: https://www.docker.com/products/docker-desktop/
After installing, restart this script.
"@
}
Ok "Docker found: $(docker --version)"

# Check Docker is running
try {
    docker info 2>&1 | Out-Null
    if ($LASTEXITCODE -ne 0) { throw }
} catch {
    Die @"
Docker Desktop is installed but not running.
Please start Docker Desktop, wait for it to become ready (whale icon in taskbar),
then re-run this script.
"@
}
Ok "Docker Desktop is running"

# Check Docker Compose v2
try {
    docker compose version 2>&1 | Out-Null
    if ($LASTEXITCODE -ne 0) { throw }
} catch {
    Die "Docker Compose v2 is required. Update Docker Desktop to 4.x or newer."
}
Ok "Docker Compose v2: $(docker compose version --short)"

# ── Generate .env ──────────────────────────────────────────────────────────────
Sec "Configuring environment"

$envFile = Join-Path $InstallDir ".env"

if (Test-Path $envFile) {
    Warn ".env already exists -- keeping existing configuration"
} else {
    # Generate cryptographically random secrets
    $chars = 'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789'
    $dbPass  = -join ((1..32) | ForEach-Object { $chars[(Get-Random -Maximum $chars.Length)] })
    $session = -join ((1..64) | ForEach-Object { $chars[(Get-Random -Maximum $chars.Length)] })

    @"
# LineOps KDS -- Windows configuration
# Generated by install.ps1 on $(Get-Date -Format 'yyyy-MM-dd HH:mm')
# Edit this file then run: docker compose up -d

# Database password (auto-generated)
DB_PASSWORD=$dbPass

# Session signing secret (auto-generated)
SESSION_SECRET=$session

# Optional: uncomment to change exposed host port (default 80)
# HOST_PORT=8080

# Optional: POS integration secrets (add as needed)
# SQUARE_WEBHOOK_SECRET=
# TOAST_WEBHOOK_SECRET=
# CLOVER_WEBHOOK_SECRET=
# LIGHTSPEED_WEBHOOK_SECRET=
# VOLANTE_WEBHOOK_SECRET=
# VOLANTE_STATION_MAP={"1":"grill","2":"cold-prep"}
# VOLANTE_HOST=https://your-ve-server.volantecloud.com
# VOLANTE_CLIENT_ID=
# VOLANTE_CLIENT_SECRET=
"@ | Set-Content -Path $envFile -Encoding UTF8

    Ok ".env generated with secure random secrets"
}

# Override port in compose if non-default
if ($Port -ne 80) {
    $env:HOST_PORT = $Port
    Info "Using port $Port (set HOST_PORT=$Port in .env to make permanent)"
}

# ── Build & start ──────────────────────────────────────────────────────────────
Sec "Starting KDS services"

Push-Location $InstallDir
try {
    $buildFlag = if ($SkipBuild) { "" } else { "--build" }

    Info "Building Docker images (this takes ~3 minutes on first run)..."
    if ($SkipBuild) {
        docker compose --env-file $envFile up -d --remove-orphans
    } else {
        docker compose --env-file $envFile up -d --build --remove-orphans
    }

    if ($LASTEXITCODE -ne 0) {
        Die "docker compose failed. Check output above for errors."
    }
} finally {
    Pop-Location
}

Ok "All containers started"

# ── Wait for health ─────────────────────────────────────────────────────────────
Sec "Waiting for API to become healthy"

$apiUrl  = "http://localhost:$Port/api/health"
$timeout = 120   # seconds
$elapsed = 0
$healthy = $false

while ($elapsed -lt $timeout) {
    try {
        $resp = Invoke-RestMethod -Uri $apiUrl -TimeoutSec 3 -ErrorAction Stop
        if ($resp.status -eq "ok" -or $resp.status -eq "healthy") {
            $healthy = $true
            break
        }
    } catch { }
    Start-Sleep -Seconds 3
    $elapsed += 3
    Write-Host "  waiting... ($elapsed/$timeout s)" -ForegroundColor DarkGray
}

if (-not $healthy) {
    Warn "API did not respond healthy within $timeout seconds."
    Warn "Services may still be starting. Check with: docker compose ps"
    Warn "Logs: docker compose logs api"
} else {
    Ok "API is healthy"
}

# ── Get LAN IP ─────────────────────────────────────────────────────────────────
$lanIp = (
    Get-NetIPAddress -AddressFamily IPv4 |
    Where-Object { $_.InterfaceAlias -notlike "*Loopback*" -and $_.PrefixOrigin -eq "Dhcp" -or $_.PrefixOrigin -eq "Manual" } |
    Where-Object { $_.IPAddress -notlike "169.*" } |
    Sort-Object -Property InterfaceMetric |
    Select-Object -First 1
).IPAddress

if (-not $lanIp) { $lanIp = "localhost" }

$portSuffix = if ($Port -ne 80) { ":$Port" } else { "" }

# ── Inject test order ──────────────────────────────────────────────────────────
Sec "Seeding test data"

try {
    Invoke-RestMethod -Method Post -Uri "http://localhost:$Port/api/test/inject-order" -TimeoutSec 10 | Out-Null
    Ok "Test order injected -- you should see it on the KDS display"
} catch {
    Warn "Could not inject test order (API may still be starting) -- try manually later:"
    Warn "  Invoke-RestMethod -Method Post http://localhost:$Port/api/test/inject-order"
}

# ── Done ───────────────────────────────────────────────────────────────────────
Sec "Installation complete!"

Write-Host "  KDS Display (point your kitchen screens here):" -ForegroundColor White
Write-Host "    http://localhost$portSuffix" -ForegroundColor Green
Write-Host "    http://${lanIp}$portSuffix   (from other devices on your network)" -ForegroundColor Green
Write-Host ""
Write-Host "  Management pages:" -ForegroundColor White
Write-Host "    Dashboard       http://localhost$portSuffix/dashboard" -ForegroundColor Cyan
Write-Host "    Integration Hub http://localhost$portSuffix/integration-hub" -ForegroundColor Cyan
Write-Host "    Template Builder http://localhost$portSuffix/template-builder" -ForegroundColor Cyan
Write-Host "    Live Monitor    http://localhost$portSuffix/live" -ForegroundColor Cyan
Write-Host ""
Write-Host "  CLI (PowerShell):" -ForegroundColor White
Write-Host "    .\bin\kds.ps1 status" -ForegroundColor DarkGray
Write-Host "    .\bin\kds.ps1 orders" -ForegroundColor DarkGray
Write-Host "    .\bin\kds.ps1 help" -ForegroundColor DarkGray
Write-Host ""
Write-Host "  Config: $envFile" -ForegroundColor DarkGray
Write-Host ""
