#!/usr/bin/env bash
# ─────────────────────────────────────────────────────────────────────────────
#  KDS Linux Installer
#
#  Installs the Kitchen Display System on any Linux machine with Docker.
#  Run as root or with sudo:
#
#    curl -fsSL https://your-domain/install.sh | sudo bash
#    — or —
#    sudo bash install.sh
#
# ─────────────────────────────────────────────────────────────────────────────

set -euo pipefail

INSTALL_DIR="/opt/kds"
CLI_PATH="/usr/local/bin/kds"
REPO_URL="${KDS_REPO_URL:-https://github.com/your-org/kds}"  # override as needed
KDS_VERSION="${KDS_VERSION:-latest}"

# ── Colours ───────────────────────────────────────────────────────────────────
RED='\033[0;31m'; GRN='\033[0;32m'; YLW='\033[0;33m'
CYN='\033[0;36m'; WHT='\033[1;37m'; DIM='\033[2m'; RST='\033[0m'

info()    { echo -e "${CYN}→${RST} $*"; }
ok()      { echo -e "${GRN}✓${RST} $*"; }
warn()    { echo -e "${YLW}⚠${RST} $*"; }
die()     { echo -e "${RED}✗ error:${RST} $*" >&2; exit 1; }
section() { echo ""; echo -e "${WHT}── $* ${RST}"; echo ""; }

[[ "$(id -u)" -eq 0 ]] || die "Please run as root: sudo bash install.sh"

section "KDS Installer — Kitchen Display System"

# ── System check ──────────────────────────────────────────────────────────────
section "Checking system requirements"

# Linux only
[[ "$(uname -s)" == "Linux" ]] || die "This installer is for Linux only."
ok "Linux detected"

# Architecture
ARCH=$(uname -m)
info "Architecture: $ARCH"

# ── Docker ────────────────────────────────────────────────────────────────────
if ! command -v docker &>/dev/null; then
  info "Docker not found — installing via get.docker.com..."
  curl -fsSL https://get.docker.com | sh
  ok "Docker installed"
else
  DOCKER_VER=$(docker --version | awk '{print $3}' | tr -d ',')
  ok "Docker found: $DOCKER_VER"
fi

# Ensure Docker is running
if ! docker info &>/dev/null 2>&1; then
  info "Starting Docker daemon..."
  systemctl start docker || service docker start || die "Could not start Docker. Start it manually and re-run."
fi

# Docker Compose v2 check
if ! docker compose version &>/dev/null 2>&1; then
  info "Installing Docker Compose plugin..."
  COMPOSE_VERSION="2.27.0"
  COMPOSE_URL="https://github.com/docker/compose/releases/download/v${COMPOSE_VERSION}/docker-compose-linux-${ARCH}"
  mkdir -p /usr/local/lib/docker/cli-plugins
  curl -fsSL "$COMPOSE_URL" -o /usr/local/lib/docker/cli-plugins/docker-compose
  chmod +x /usr/local/lib/docker/cli-plugins/docker-compose
  ok "Docker Compose v2 installed"
else
  ok "Docker Compose v2 found: $(docker compose version --short)"
fi

# jq (used by the CLI)
if ! command -v jq &>/dev/null; then
  info "Installing jq..."
  if command -v apt-get &>/dev/null; then
    apt-get install -y -q jq
  elif command -v yum &>/dev/null; then
    yum install -y -q jq
  elif command -v apk &>/dev/null; then
    apk add --no-cache jq
  else
    warn "Could not auto-install jq. The CLI may not format output correctly."
  fi
  command -v jq &>/dev/null && ok "jq installed"
fi

# ── Install KDS files ─────────────────────────────────────────────────────────
section "Installing KDS"

mkdir -p "$INSTALL_DIR"/{docker,bin,data}
info "Install directory: $INSTALL_DIR"

# Copy docker files (if running from the source repo)
if [[ -f "$(dirname "$0")/docker-compose.yml" ]]; then
  info "Copying files from source directory..."
  cp "$(dirname "$0")/docker-compose.yml"      "$INSTALL_DIR/docker-compose.yml"
  cp "$(dirname "$0")/docker/nginx.conf"        "$INSTALL_DIR/docker/nginx.conf"
  cp "$(dirname "$0")/docker/nginx-kds-default.conf" "$INSTALL_DIR/docker/nginx-kds-default.conf"
  cp "$(dirname "$0")/docker/Dockerfile.api"    "$INSTALL_DIR/docker/Dockerfile.api"
  cp "$(dirname "$0")/docker/Dockerfile.web"    "$INSTALL_DIR/docker/Dockerfile.web"
  # Copy full source for building
  rsync -a --exclude=node_modules --exclude=dist --exclude=.git \
    "$(dirname "$0")/" "$INSTALL_DIR/src/" 2>/dev/null || \
    cp -r "$(dirname "$0")/." "$INSTALL_DIR/src/"
  ok "Source files copied"
else
  warn "Running without source — pulling pre-built images only"
  # Download docker-compose.yml from the repo
  curl -fsSL "${REPO_URL}/raw/main/docker-compose.yml" -o "$INSTALL_DIR/docker-compose.yml"
  curl -fsSL "${REPO_URL}/raw/main/docker/nginx.conf"  -o "$INSTALL_DIR/docker/nginx.conf"
  ok "Configuration downloaded"
fi

# ── Generate .env ──────────────────────────────────────────────────────────────
section "Generating configuration"

ENV_FILE="$INSTALL_DIR/.env"
if [[ -f "$ENV_FILE" ]]; then
  warn ".env already exists — keeping existing configuration"
else
  DB_PASS=$(tr -dc 'a-zA-Z0-9' </dev/urandom | head -c 32 || true)
  SESSION_SECRET=$(tr -dc 'a-zA-Z0-9' </dev/urandom | head -c 64 || true)
  cat > "$ENV_FILE" <<EOF
# KDS Configuration — generated by install.sh
# Edit this file to customise your installation

# Database password (auto-generated — do not share)
DB_PASSWORD=${DB_PASS}

# Session secret (auto-generated — do not share)
SESSION_SECRET=${SESSION_SECRET}

# Optional: override the API port exposed to localhost (default 3000)
# API_PORT=3000

# Optional: set a custom store name
# KDS_STORE_NAME=My Restaurant
EOF
  chmod 600 "$ENV_FILE"
  ok ".env generated with secure random secrets"
fi

# ── Install CLI ────────────────────────────────────────────────────────────────
section "Installing kds CLI"

CLI_SRC="$(dirname "$0")/bin/kds"
if [[ -f "$CLI_SRC" ]]; then
  cp "$CLI_SRC" "$CLI_PATH"
else
  curl -fsSL "${REPO_URL}/raw/main/bin/kds" -o "$CLI_PATH"
fi

chmod +x "$CLI_PATH"
# Embed the install dir so the CLI knows where to find docker-compose.yml
sed -i "s|KDS_DIR=.*|KDS_DIR=\"${INSTALL_DIR}\"|" "$CLI_PATH" 2>/dev/null || true
ok "CLI installed at $CLI_PATH"

# ── Start services ─────────────────────────────────────────────────────────────
section "Starting KDS services"

cd "$INSTALL_DIR"
docker compose --env-file "$ENV_FILE" up -d --build
ok "KDS is running"

# ── Get LAN IP ────────────────────────────────────────────────────────────────
LAN_IP=$(ip -4 addr show scope global 2>/dev/null | grep -oP '(?<=inet\s)\d+(\.\d+){3}' | head -1) || \
LAN_IP=$(hostname -I 2>/dev/null | awk '{print $1}') || LAN_IP="<your-server-ip>"

section "Installation complete!"

echo -e "  ${WHT}KDS Display (tablets/screens)${RST}"
echo -e "    ${GRN}http://${LAN_IP}/${RST}"
echo ""
echo -e "  ${WHT}Admin / Template Builder${RST}"
echo -e "    ${GRN}http://${LAN_IP}/admin${RST}"
echo ""
echo -e "  ${WHT}Quick commands${RST}"
echo -e "    ${CYN}kds status${RST}           — live system overview"
echo -e "    ${CYN}kds orders${RST}           — show active orders"
echo -e "    ${CYN}kds orders bump 101${RST}  — bump order #101"
echo -e "    ${CYN}kds logs api${RST}         — tail API logs"
echo -e "    ${CYN}kds ip${RST}               — show LAN address"
echo -e "    ${CYN}kds help${RST}             — full command reference"
echo ""
echo -e "  ${DIM}Config: ${INSTALL_DIR}/.env${RST}"
echo ""
