// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/kds-display/ElevatedCard.tsx": () => import("../components/mockups/kds-display/ElevatedCard.tsx"),
  "./components/mockups/kds-display/StructuredGrid.tsx": () => import("../components/mockups/kds-display/StructuredGrid.tsx")
};
