// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/kds-display/ElevatedCard.tsx": () => import("../components/mockups/kds-display/ElevatedCard.tsx"),
  "./components/mockups/kds-display/Spotlight.tsx": () => import("../components/mockups/kds-display/Spotlight.tsx"),
  "./components/mockups/kds-display/StationBoard.tsx": () => import("../components/mockups/kds-display/StationBoard.tsx"),
  "./components/mockups/kds-display/StructuredGrid.tsx": () => import("../components/mockups/kds-display/StructuredGrid.tsx"),
  "./components/mockups/kds-display/TemplateBuilder.tsx": () => import("../components/mockups/kds-display/TemplateBuilder.tsx"),
  "./components/mockups/kds-display/TicketRail.tsx": () => import("../components/mockups/kds-display/TicketRail.tsx")
};
