#Requires -Version 5.1
<#
.SYNOPSIS
    LineOps KDS — Full-Stack Setup Script (Windows)

.DESCRIPTION
    Installs the complete LineOps KDS stack on a Windows machine with Docker Desktop.
    Deploys: PostgreSQL · API Server · KDS Display · Back-office Dashboard

    Run from an elevated PowerShell session (Run as Administrator):

        irm https://github.com/abhaypatial/Lineops_KDS/raw/main/install/lineops-kds-setup.ps1 | iex

    Or clone the repo and run locally:

        powershell -ExecutionPolicy Bypass -File install\lineops-kds-setup.ps1

.PARAMETER InstallDir
    Installation directory (default: C:\LineOps\KDS)

.PARAMETER Port
    Host port for the web interface (default: 80)

.PARAMETER SkipBuild
    Skip rebuilding Docker images (use cached images)
#>
param(
    [string] $InstallDir = "C:\LineOps\KDS",
    [int]    $Port       = 80,
    [switch] $SkipBuild
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

function Info  ($m) { Write-Host "  -> $m" -ForegroundColor Cyan    }
function Ok    ($m) { Write-Host "  OK $m" -ForegroundColor Green   }
function Warn  ($m) { Write-Host "  !! $m" -ForegroundColor Yellow  }
function Die   ($m) { Write-Host "  ERR $m" -ForegroundColor Red; exit 1 }
function Sec   ($m) { Write-Host ""; Write-Host "  -- $m" -ForegroundColor White; Write-Host "" }

Clear-Host
Write-Host ""
Write-Host "   LineOps KDS — Full-Stack Setup" -ForegroundColor DarkYellow
Write-Host "   Kitchen Display System  ·  Windows Installer  ·  v1.3.0" -ForegroundColor DarkGray
Write-Host ""

# ── Admin check ───────────────────────────────────────────────────────────────
$isAdmin = ([Security.Principal.WindowsPrincipal][Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole(
    [Security.Principal.WindowsBuiltInRole]::Administrator)
if (-not $isAdmin) { Die "Run as Administrator (right-click PowerShell → Run as Administrator)." }
Ok "Running as Administrator"

# ── Docker ────────────────────────────────────────────────────────────────────
Sec "Docker"

if (-not (Get-Command docker -ErrorAction SilentlyContinue)) {
    Warn "Docker Desktop not found."
    Info "Download and install Docker Desktop from https://www.docker.com/products/docker-desktop/"
    Info "Then re-run this script."
    exit 1
}
Ok "Docker found: $(docker --version)"

try { docker info | Out-Null }
catch { Die "Docker daemon is not running. Start Docker Desktop and retry." }

if (-not (docker compose version 2>$null)) { Die "Docker Compose v2 not found. Update Docker Desktop to v4.0+." }
Ok "Docker Compose: $(docker compose version --short)"

# ── Clone / update repo ───────────────────────────────────────────────────────
Sec "Installing LineOps KDS"

if (-not (Test-Path $InstallDir)) { New-Item -ItemType Directory -Path $InstallDir -Force | Out-Null }

if (Test-Path (Join-Path $InstallDir ".git")) {
    Info "Updating existing install at $InstallDir ..."
    Push-Location $InstallDir
    try { git pull --ff-only origin main | Out-Null; Ok "Repository updated" }
    catch { Warn "Git pull failed — continuing with existing files." }
    Pop-Location
} elseif (Get-Command git -ErrorAction SilentlyContinue) {
    Info "Cloning repository to $InstallDir ..."
    git clone --depth 1 "https://github.com/abhaypatial/Lineops_KDS" $InstallDir
    Ok "Repository cloned"
} else {
    Info "Downloading release archive ..."
    $zip = Join-Path $env:TEMP "lineops-kds.zip"
    Invoke-WebRequest "https://github.com/abhaypatial/Lineops_KDS/archive/refs/heads/main.zip" -OutFile $zip
    Expand-Archive $zip -DestinationPath $env:TEMP -Force
    Copy-Item "$env:TEMP\Lineops_KDS-main\*" $InstallDir -Recurse -Force
    Ok "Files downloaded"
}

# ── Generate .env ─────────────────────────────────────────────────────────────
Sec "Configuring environment"

$envFile = Join-Path $InstallDir ".env"
if (Test-Path $envFile) {
    Warn ".env already exists — skipping (delete it to regenerate secrets)."
} else {
    $chars = 'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789'
    $rng   = [System.Security.Cryptography.RandomNumberGenerator]::Create()
    function RandStr([int]$len) {
        $buf = New-Object byte[] $len
        $rng.GetBytes($buf)
        -join ($buf | ForEach-Object { $chars[$_ % $chars.Length] })
    }
    $dbPass  = RandStr 24
    $session = RandStr 40
    @"
# Generated by LineOps KDS installer on $(Get-Date -Format "yyyy-MM-dd HH:mm") UTC
# Keep this file private. Delete to regenerate secrets.

DB_PASSWORD=$dbPass
SESSION_SECRET=$session

# ADMIN_PASSWORD=change_me
# HOST_PORT=$Port
"@ | Set-Content $envFile -Encoding UTF8
    Ok ".env generated with secure random secrets"
}

# ── Build and start ───────────────────────────────────────────────────────────
Sec "Starting LineOps KDS services"

Push-Location $InstallDir
$buildFlag = if ($SkipBuild) { "" } else { "--build" }
Invoke-Expression "docker compose up -d $buildFlag --remove-orphans"
Ok "All services started (postgres · api-server · kds-display · nginx)"
Pop-Location

# ── Access info ───────────────────────────────────────────────────────────────
$lanIp = (Get-NetIPAddress -AddressFamily IPv4 -PrefixOrigin Dhcp,Manual `
    -ErrorAction SilentlyContinue | Where-Object { $_.IPAddress -notmatch '^127\.' } |
    Select-Object -First 1).IPAddress
if (-not $lanIp) { $lanIp = "your-server-ip" }

Write-Host ""
Write-Host "  ============================================================" -ForegroundColor DarkYellow
Write-Host ""
Write-Host "  OK  LineOps KDS is running!" -ForegroundColor Green
Write-Host ""
Write-Host "  KDS Display (kitchen screens):" -NoNewline; Write-Host "  http://$lanIp/"          -ForegroundColor Cyan
Write-Host "  Back-office dashboard:        " -NoNewline; Write-Host "  http://$lanIp/dashboard" -ForegroundColor Cyan
Write-Host "  API health check:             " -NoNewline; Write-Host "  http://$lanIp/api/health"-ForegroundColor Cyan
Write-Host ""
Write-Host "  Point kitchen tablets and wall displays at the KDS Display URL." -ForegroundColor DarkGray
Write-Host "  Managers and expo staff use the Back-office dashboard."          -ForegroundColor DarkGray
Write-Host ""
Write-Host "  ============================================================" -ForegroundColor DarkYellow
Write-Host ""
