#!/usr/bin/env bash
# ─────────────────────────────────────────────────────────────────────────────
#  LineOps KDS — One-Prompt Linux Installer
#
#  Run this single command on any Linux machine:
#
#    curl -fsSL https://github.com/abhaypatial/Lineops_KDS/raw/main/install/linux.sh | sudo bash
#
#  What it does:
#    1. Installs Docker if not present
#    2. Clones / downloads the KDS repo to /opt/kds
#    3. Generates a .env with secure random secrets
#    4. Builds and starts all services with Docker Compose
#    5. Installs the `kds` CLI to /usr/local/bin
#    6. Prints the URL your kitchen screens should open
# ─────────────────────────────────────────────────────────────────────────────

set -euo pipefail

INSTALL_DIR="/opt/kds"
CLI_PATH="/usr/local/bin/kds"
REPO_URL="https://github.com/abhaypatial/Lineops_KDS"
KDS_VERSION="${KDS_VERSION:-main}"

# ── Colours ───────────────────────────────────────────────────────────────────
RED='\033[0;31m'; GRN='\033[0;32m'; YLW='\033[0;33m'
CYN='\033[0;36m'; WHT='\033[1;37m'; DIM='\033[2m'; RST='\033[0m'

info()    { echo -e "${CYN}→${RST} $*"; }
ok()      { echo -e "${GRN}✓${RST} $*"; }
warn()    { echo -e "${YLW}⚠${RST}  $*"; }
die()     { echo -e "${RED}✗ error:${RST} $*" >&2; exit 1; }
section() { echo ""; echo -e "${WHT}── $* ${RST}"; echo ""; }

[[ "$(id -u)" -eq 0 ]] || die "Please run as root: sudo bash install/linux.sh"

clear
echo -e "${WHT}"
echo "  ██╗     ██╗███╗   ██╗███████╗ ██████╗ ██████╗ ███████╗"
echo "  ██║     ██║████╗  ██║██╔════╝██╔═══██╗██╔══██╗██╔════╝"
echo "  ██║     ██║██╔██╗ ██║█████╗  ██║   ██║██████╔╝███████╗"
echo "  ██║     ██║██║╚██╗██║██╔══╝  ██║   ██║██╔═══╝ ╚════██║"
echo "  ███████╗██║██║ ╚████║███████╗╚██████╔╝██║     ███████║"
echo "  ╚══════╝╚═╝╚═╝  ╚═══╝╚══════╝ ╚═════╝ ╚═╝     ╚══════╝"
echo -e "${DIM}  Kitchen Display System  •  lineops.io${RST}"
echo ""

section "System requirements"

[[ "$(uname -s)" == "Linux" ]] || die "This installer is for Linux only."
ok "Linux detected ($(uname -m))"

# ── Docker ────────────────────────────────────────────────────────────────────
if ! command -v docker &>/dev/null; then
  info "Docker not found — installing via get.docker.com..."
  curl -fsSL https://get.docker.com | sh
  ok "Docker installed"
else
  ok "Docker found: $(docker --version | awk '{print $3}' | tr -d ',')"
fi

if ! docker info &>/dev/null 2>&1; then
  info "Starting Docker daemon..."
  systemctl start docker 2>/dev/null || service docker start 2>/dev/null || \
    die "Could not start Docker. Start it manually then re-run."
fi

if ! docker compose version &>/dev/null 2>&1; then
  info "Installing Docker Compose plugin..."
  ARCH=$(uname -m)
  COMPOSE_URL="https://github.com/docker/compose/releases/download/v2.27.0/docker-compose-linux-${ARCH}"
  mkdir -p /usr/local/lib/docker/cli-plugins
  curl -fsSL "$COMPOSE_URL" -o /usr/local/lib/docker/cli-plugins/docker-compose
  chmod +x /usr/local/lib/docker/cli-plugins/docker-compose
  ok "Docker Compose v2 installed"
else
  ok "Docker Compose v2 found: $(docker compose version --short)"
fi

# jq (used by the CLI)
if ! command -v jq &>/dev/null; then
  info "Installing jq..."
  if command -v apt-get &>/dev/null; then
    apt-get install -y -q jq
  elif command -v yum &>/dev/null; then
    yum install -y -q jq
  elif command -v dnf &>/dev/null; then
    dnf install -y -q jq
  else
    warn "Could not install jq automatically. Install it manually for full CLI support."
  fi
fi

# ── Download / update repo ────────────────────────────────────────────────────
section "Installing KDS files"

if [[ -d "${INSTALL_DIR}/.git" ]]; then
  info "Updating existing install in ${INSTALL_DIR}..."
  git -C "$INSTALL_DIR" pull --ff-only origin "$KDS_VERSION" || \
    warn "Git pull failed — continuing with existing files."
  ok "Files updated"
elif command -v git &>/dev/null; then
  info "Cloning repository to ${INSTALL_DIR}..."
  git clone --depth 1 --branch "$KDS_VERSION" "$REPO_URL" "$INSTALL_DIR"
  ok "Repository cloned"
else
  info "Downloading release archive..."
  mkdir -p "$INSTALL_DIR"
  curl -fsSL "${REPO_URL}/archive/refs/heads/${KDS_VERSION}.tar.gz" \
    | tar xz --strip-components=1 -C "$INSTALL_DIR"
  ok "Files downloaded"
fi

# ── Generate .env ─────────────────────────────────────────────────────────────
section "Configuring environment"

ENV_FILE="${INSTALL_DIR}/.env"
if [[ -f "$ENV_FILE" ]]; then
  warn ".env already exists — skipping generation (delete it to regenerate)."
else
  DB_PASSWORD=$(head -c 32 /dev/urandom | base64 | tr -dc 'a-zA-Z0-9' | head -c 24)
  SESSION_SECRET=$(head -c 48 /dev/urandom | base64 | tr -dc 'a-zA-Z0-9' | head -c 40)

  cat > "$ENV_FILE" <<EOF
# Generated by LineOps KDS installer on $(date -u +"%Y-%m-%d %H:%M UTC")
# Edit this file to customise your installation.

DB_PASSWORD=${DB_PASSWORD}
SESSION_SECRET=${SESSION_SECRET}

# ── Admin password (leave blank for open access on trusted LAN) ──────────────
# ADMIN_PASSWORD=change_me

# ── Feature flags ─────────────────────────────────────────────────────────────
# ALLOW_TEST_ORDERS=true
# HIDDEN_INTEGRATIONS=

# ── Network ───────────────────────────────────────────────────────────────────
# HOST_PORT=80
EOF
  ok ".env generated with secure random secrets"
fi

# ── Install CLI ───────────────────────────────────────────────────────────────
section "Installing kds CLI"

cp "${INSTALL_DIR}/bin/kds" "$CLI_PATH"
chmod +x "$CLI_PATH"
sed -i "s|KDS_DIR=.*|KDS_DIR=\"${INSTALL_DIR}\"|" "$CLI_PATH" 2>/dev/null || true
ok "kds CLI installed at ${CLI_PATH}"

# ── Build and start services ──────────────────────────────────────────────────
section "Starting KDS services"

cd "$INSTALL_DIR"
docker compose pull --quiet 2>/dev/null || true
docker compose up -d --build --remove-orphans
ok "All KDS services started"

# ── Print access info ─────────────────────────────────────────────────────────
LAN_IP=$(ip -4 addr show scope global 2>/dev/null | grep -oP '(?<=inet\s)\d+(\.\d+){3}' | head -1 \
         || hostname -I 2>/dev/null | awk '{print $1}' || echo "your-server-ip")

echo ""
echo -e "${WHT}────────────────────────────────────────────────────────────${RST}"
echo -e ""
echo -e "  ${GRN}✓ LineOps KDS is running!${RST}"
echo ""
echo -e "  ${WHT}KDS Display (kitchen screens):${RST}  ${CYN}http://${LAN_IP}/${RST}"
echo -e "  ${WHT}Management dashboard:${RST}           ${CYN}http://${LAN_IP}/dashboard${RST}"
echo -e "  ${WHT}Health check:${RST}                   ${CYN}http://${LAN_IP}/api/health${RST}"
echo ""
echo -e "  Point your kitchen tablets and displays at the KDS Display URL."
echo ""
echo -e "  ${DIM}Run  kds status  at any time to see a live system overview.${RST}"
echo -e "  ${DIM}Run  kds --help  for all available commands.${RST}"
echo ""
echo -e "${WHT}────────────────────────────────────────────────────────────${RST}"
echo ""
