#Requires -Version 5.1
# DEPRECATED — Use lineops-kds-setup.ps1 instead:
#   irm https://github.com/abhaypatial/Lineops_KDS/raw/main/install/lineops-kds-setup.ps1 | iex
<#
.SYNOPSIS
    LineOps KDS — Windows Installer (legacy entry point)

.DESCRIPTION
    Installs the LineOps KDS on a Windows machine with Docker Desktop.

    Run from an elevated PowerShell session (Run as Administrator):

        irm https://github.com/abhaypatial/Lineops_KDS/raw/main/install/windows.ps1 | iex

    Or clone the repo first and run:

        powershell -ExecutionPolicy Bypass -File install\windows.ps1

.PARAMETER InstallDir
    Where to install KDS (default: C:\LineOps\KDS)

.PARAMETER Port
    Host port for the KDS web interface (default: 80)

.PARAMETER SkipBuild
    Skip rebuilding Docker images (use cached images)
#>
param(
    [string] $InstallDir = "C:\LineOps\KDS",
    [int]    $Port       = 80,
    [switch] $SkipBuild
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

function Info  ($m) { Write-Host "  -> $m" -ForegroundColor Cyan }
function Ok    ($m) { Write-Host "  OK $m" -ForegroundColor Green }
function Warn  ($m) { Write-Host "  !! $m" -ForegroundColor Yellow }
function Die   ($m) { Write-Host "  ERR $m" -ForegroundColor Red -NoNewline; Write-Host ""; exit 1 }
function Sec   ($m) { Write-Host ""; Write-Host "-- $m" -ForegroundColor White; Write-Host "" }

Clear-Host
Write-Host ""
Write-Host "  LineOps KDS — Kitchen Display System" -ForegroundColor White
Write-Host "  One-prompt Windows installer" -ForegroundColor DarkGray
Write-Host ""

# ── Admin check ───────────────────────────────────────────────────────────────
$isAdmin = ([Security.Principal.WindowsPrincipal][Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole(
    [Security.Principal.WindowsBuiltInRole]::Administrator
)
if (-not $isAdmin) {
    Die "Run this script as Administrator (right-click PowerShell -> Run as Administrator)."
}
Ok "Running as Administrator"

# ── Docker check ──────────────────────────────────────────────────────────────
Sec "Checking Docker"

if (-not (Get-Command docker -ErrorAction SilentlyContinue)) {
    Warn "Docker not found."
    Write-Host ""
    Write-Host "  Please install Docker Desktop for Windows, then re-run this installer." -ForegroundColor Yellow
    Write-Host "  Download: https://docs.docker.com/desktop/install/windows-install/" -ForegroundColor Cyan
    Write-Host ""
    exit 1
}

try {
    $null = docker info 2>&1
    Ok "Docker Desktop is running"
} catch {
    Die "Docker is installed but not running. Start Docker Desktop and try again."
}

try {
    $dcVersion = docker compose version --short 2>&1
    Ok "Docker Compose v2 found: $dcVersion"
} catch {
    Die "Docker Compose v2 not found. Update Docker Desktop to the latest version."
}

# ── Download / update repo ────────────────────────────────────────────────────
Sec "Installing KDS files to $InstallDir"

$repoUrl    = "https://github.com/abhaypatial/Lineops_KDS"
$archiveUrl = "$repoUrl/archive/refs/heads/main.zip"
$tmpZip     = Join-Path $env:TEMP "lineops-kds.zip"
$tmpDir     = Join-Path $env:TEMP "lineops-kds-src"

if (Test-Path $InstallDir) {
    Warn "Directory $InstallDir already exists — updating files."
} else {
    New-Item -ItemType Directory -Path $InstallDir -Force | Out-Null
}

Info "Downloading from $repoUrl..."
Invoke-WebRequest -Uri $archiveUrl -OutFile $tmpZip -UseBasicParsing
Expand-Archive -Path $tmpZip -DestinationPath $tmpDir -Force

# Copy extracted files (repo is in a subfolder like Lineops_KDS-main)
$extracted = Get-ChildItem $tmpDir | Where-Object { $_.PSIsContainer } | Select-Object -First 1
if ($extracted) {
    Copy-Item -Path "$($extracted.FullName)\*" -Destination $InstallDir -Recurse -Force
    Ok "Files installed to $InstallDir"
} else {
    Die "Failed to extract archive."
}

# Clean up temp files
Remove-Item $tmpZip, $tmpDir -Recurse -Force -ErrorAction SilentlyContinue

# ── Generate .env ─────────────────────────────────────────────────────────────
Sec "Configuring environment"

$envFile = Join-Path $InstallDir ".env"

if (Test-Path $envFile) {
    Warn ".env already exists — skipping generation."
} else {
    $dbPwd  = [System.Web.Security.Membership]::GeneratePassword(24, 4)
    $secret = [System.Web.Security.Membership]::GeneratePassword(40, 6)

    # Fallback if System.Web is not available
    if (-not $dbPwd) {
        $dbPwd  = -join ((48..57) + (65..90) + (97..122) | Get-Random -Count 24 | ForEach-Object { [char]$_ })
        $secret = -join ((48..57) + (65..90) + (97..122) | Get-Random -Count 40 | ForEach-Object { [char]$_ })
    }

    $envContent = @"
# Generated by LineOps KDS installer
# Edit this file to customise your installation.

DB_PASSWORD=$dbPwd
SESSION_SECRET=$secret

# -- Admin password (leave blank for open access on trusted LAN) --------------
# ADMIN_PASSWORD=change_me

# -- Feature flags ------------------------------------------------------------
# ALLOW_TEST_ORDERS=true
# HIDDEN_INTEGRATIONS=

# -- Network ------------------------------------------------------------------
HOST_PORT=$Port
"@
    Set-Content -Path $envFile -Value $envContent -Encoding UTF8
    Ok ".env generated with secure random secrets"
}

# ── Start services ────────────────────────────────────────────────────────────
Sec "Starting KDS services"

Set-Location $InstallDir

if ($SkipBuild) {
    docker compose up -d --remove-orphans
} else {
    docker compose up -d --build --remove-orphans
}

if ($LASTEXITCODE -ne 0) { Die "docker compose up failed. Check the output above." }
Ok "All KDS services started"

# ── Print access info ─────────────────────────────────────────────────────────
$lanIp = (Get-NetIPAddress -AddressFamily IPv4 |
    Where-Object { $_.PrefixOrigin -ne "WellKnown" -and $_.IPAddress -ne "127.0.0.1" } |
    Select-Object -First 1).IPAddress

$portSuffix = if ($Port -eq 80) { "" } else { ":$Port" }

Write-Host ""
Write-Host "  ────────────────────────────────────────────────────────" -ForegroundColor White
Write-Host ""
Write-Host "  OK  LineOps KDS is running!" -ForegroundColor Green
Write-Host ""
Write-Host "  KDS Display (kitchen screens):  http://$lanIp$portSuffix/" -ForegroundColor Cyan
Write-Host "  Management dashboard:            http://$lanIp$portSuffix/dashboard" -ForegroundColor Cyan
Write-Host "  Health check:                    http://$lanIp$portSuffix/api/health" -ForegroundColor Cyan
Write-Host ""
Write-Host "  Point your kitchen tablets and displays at the KDS Display URL." -ForegroundColor Gray
Write-Host ""
Write-Host "  Installed at: $InstallDir" -ForegroundColor DarkGray
Write-Host "  ────────────────────────────────────────────────────────" -ForegroundColor White
Write-Host ""
